### ISSUE TITLE
API SDK + requestPaymentP2P = error illegal_params

### ISSUE THREAD

**Issue by pochtar** [melnikovdv/PHP-Yandex.Money-API-SDK#11]
http://clubs.ya.ru/moneyapi/2930

**Comment by OneHalf3544** [comment]
Наверняка это был платеж самому себе.
Добавьте уже в библиотеку поле "error_description" в request-payment. 
Там для таких явных ошибок приходит текст с описанием проблемы.

**Comment by melnikovdv** [comment]
Да, добавим =)
