### ISSUE TITLE
Status of the operation

### ISSUE THREAD

**Issue by mikield** [melnikovdv/PHP-Yandex.Money-API-SDK#15]
Если кому-то понадобится узнать статус операции. Добавить в class YM_Operation код в инициализацию класса.

if (isset($operation['status']))
            $this->status = $operation['status'];

Потому что если нужно будет узнать или нам передали деньги с протекцией, то статус будет in_proccess. А если нет тогда success

Благодарю за внимание ))

**Comment by wielski** [comment]
same problem. thank you so much for solution!
