### ISSUE TITLE
при получении token unauthorized_client

### ISSUE THREAD

**Issue by pehser** [melnikovdv/PHP-Yandex.Money-API-SDK#20]
при по пытке получить токет 
Этому приложению отказано в доступе. 
Свяжитесь с его разработчиком и укажите сведения об ошибке (unauthorized_client).

подскажите в чем может быть ошибка?

**Comment by melnikovdv** [comment]
Во-первых, вы используете устаревшую библиотеку, на главной странице указан [актуальный репозиторий](https://github.com/yandex-money/yandex-money-sdk-php), обновитесь, пожалуйста.

После этого, если ошибка останется, откройте тикет в указанном репозитории, указав параметры запроса и прочую необходимую информацию.
