### ISSUE TITLE
Error: unauthorized_client

### ISSUE THREAD

**Issue by Mercel** [melnikovdv/PHP-Yandex.Money-API-SDK#8]
Hello,

I have problem with use sample. I update info in consts.php file and when go to website I get error "Yandex.Money PHP SDK sample app. Error: unauthorized_client"

My website: http://speak-up.pixelsunited.megiteam.pl/shop/money

**Comment by melnikovdv** [comment]
You know, I tried to create new app at https://sp-money.yandex.ru/myservices/new.xml, changed data at consts.php  and succeded in sample. Make sure that you entered consts correctly (copy-paste them again) and try once more.

**Comment by Mercel** [comment]
Thank you for answer,

I try change data at consts.php and still I have problem, but  now I get error:

Notice: after you received access_token you should store it to your app's storage and Notice: Undefined offset: 0 in /home/pixelsunited/www/speak-up/shop/money/index.php on line 72 Fatal error: Call to a member function getOperationId() on a non-object in /home/pixelsunited/www/speak-up/shop/money/index.php on line 72

**Comment by melnikovdv** [comment]
Now it's okey. You got error, which says that your account history is empty.

``` php
$operations = $resp->getOperations();
$requestId = $operations[0]->getOperationId();
```

Obviously, when you have no operations in array you'll get an exception. I'll fix the example with check for not null array of operations.

**Comment by melnikovdv** [comment]
That's it, I've updated index.php

**Comment by Mercel** [comment]
Thank you
